name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production   # ðŸ‘ˆ THIS LINE IS REQUIRED

    steps:
      - name: Deploy to VPS
        uses: actions/checkout@v4
      
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "USERNAME MISSING"; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "PASSWORD MISSING"; fi

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

            # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          registry: ${{ secrets.AZURE_REGISTRY_NAME }}  # e.g., myregistry.azurecr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}/dotnetgetting:v2 .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}/dotnetgetting:v2

      - name: Deploy to Server (Password)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.AZURE_REGISTRY_NAME }}/dotnetgetting:v2
            docker stop myapp || true
            docker rm myapp || true
            docker run -d \
              -p 8080:8080 \
              --restart always \
              --name myapp \
              ${{ secrets.AZURE_REGISTRY_NAME }}/dotnetgetting:v2
